"""sync models with db

Revision ID: 4128e504f05e
Revises: 41fd85a02af6
Create Date: 2026-02-21 03:07:49.980146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4128e504f05e'
down_revision: Union[str, Sequence[str], None] = '41fd85a02af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'topic',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.create_index('uq_booking_active_slot_date', 'bookings', ['when', 'time_slot_id'], unique=True, postgresql_where=sa.text("status <> 'CANCELLED'"))
    op.create_foreign_key(None, 'bookings', 'time_slots', ['time_slot_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['guest_id'], ['id'])
    op.alter_column('calendars', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(None, 'calendars', 'users', ['host_id'], ['id'])
    op.create_foreign_key(None, 'match_requests', 'users', ['guest_id'], ['id'])
    op.alter_column('time_slots', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('time_slots', 'calendar_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('time_slots', 'calendar_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('time_slots', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'match_requests', type_='foreignkey')
    op.drop_constraint(None, 'calendars', type_='foreignkey')
    op.alter_column('calendars', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index('uq_booking_active_slot_date', table_name='bookings', postgresql_where=sa.text("status <> 'CANCELLED'"))
    op.alter_column('bookings', 'topic',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
