"""Add post media table

Revision ID: 33c1f955a50f
Revises: e41741d35be2
Create Date: 2026-02-01 06:57:49.721962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33c1f955a50f'
down_revision: Union[str, Sequence[str], None] = 'e41741d35be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    # ENUM 타입 생성
    sa.Enum('IMAGE', 'VIDEO', name='mediatype').create(bind, checkfirst=True)

    # 신규 컬럼 추가
    op.add_column('post_media', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('post_media', sa.Column('sort_order', sa.Integer(), nullable=False, server_default=sa.text("0")))

    # media_type 컬럼 재생성
    op.drop_column('post_media', 'media_type')
    op.add_column('post_media', sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=False, server_default='IMAGE'))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_media', type_='foreignkey')
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.alter_column('post_media', 'media_type',
               existing_type=sa.Enum('IMAGE', 'VIDEO', name='mediatype'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('post_media', 'sort_order')
    op.drop_column('post_media', 'url')
    # ### end Alembic commands ###
