"""add match request and post calendar fields

Revision ID: f6ff0d9f3bc7
Revises: 9a4feb03dc40
Create Date: 2026-02-06 09:54:55.815329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision: str = 'f6ff0d9f3bc7'
down_revision: Union[str, Sequence[str], None] = '9a4feb03dc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. match_requests 테이블 생성
    op.create_table('match_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('guest_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'guest_id', name='uq_post_guest_application')
    )
    op.create_index(op.f('ix_match_requests_guest_id'), 'match_requests', ['guest_id'], unique=False)
    op.create_index(op.f('ix_match_requests_post_id'), 'match_requests', ['post_id'], unique=False)
    
    # [삭제됨] oauth_accounts 테이블 생성 코드 (이미 존재하므로 삭제)
    # op.create_table('oauth_accounts', ...)

    # 2. Booking Type Enum 생성 및 컬럼 추가
    # (주의: 만약 bookingtype Enum도 이미 있다고 에러나면 이 부분도 지워야 할 수 있습니다. 일단은 둡니다.)
    booking_type_enum = sa.Enum('LESSON', 'HOLIDAY', name='bookingtype')
    booking_type_enum.create(op.get_bind(), checkfirst=True) # checkfirst=True 추가로 안전하게

    op.add_column('bookings', sa.Column('type', sa.Enum('LESSON', 'HOLIDAY', name='bookingtype'), nullable=False, server_default='LESSON'))

    op.create_foreign_key(None, 'calendars', 'users', ['host_id'], ['id'])
    op.add_column('posts', sa.Column('time_slot_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('when', sa.Date(), nullable=True))
    
    op.create_foreign_key(None, 'time_slots', 'calendars', ['calendar_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'CUSTOMER'::text"))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint('uq_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'CUSTOMER'::text"))
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    
    op.drop_column('posts', 'when')
    op.drop_column('posts', 'time_slot_id')
    op.drop_constraint(None, 'calendars', type_='foreignkey')
    
    op.drop_column('bookings', 'type')
    
    # [수정됨] oauth_accounts 삭제 부분도 제거 (생성을 안 했으니 삭제도 안 함)
    # op.drop_table('oauth_accounts')

    op.drop_index(op.f('ix_match_requests_post_id'), table_name='match_requests')
    op.drop_index(op.f('ix_match_requests_guest_id'), table_name='match_requests')
    op.drop_table('match_requests')

    booking_type_enum = sa.Enum('LESSON', 'HOLIDAY', name='bookingtype')
    booking_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###