"""add match request and post calendar fields

Revision ID: f6ff0d9f3bc7
Revises: 9a4feb03dc40
Create Date: 2026-02-06 09:54:55.815329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision: str = 'f6ff0d9f3bc7'
down_revision: Union[str, Sequence[str], None] = '9a4feb03dc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. match_requests 테이블 생성
    op.create_table('match_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('guest_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'guest_id', name='uq_post_guest_application')
    )
    op.create_index(op.f('ix_match_requests_guest_id'), 'match_requests', ['guest_id'], unique=False)
    op.create_index(op.f('ix_match_requests_post_id'), 'match_requests', ['post_id'], unique=False)
    
    # 2. oauth_accounts 테이블 생성
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_provider_provider_account_id')
    )
    
    # 3. Booking Type Enum 생성 및 컬럼 추가 (수정됨)
    booking_type_enum = sa.Enum('LESSON', 'HOLIDAY', name='bookingtype')
    booking_type_enum.create(op.get_bind())
    op.add_column('bookings', sa.Column('type', sa.Enum('LESSON', 'HOLIDAY', name='bookingtype'), nullable=False, server_default='LESSON'))

    # [삭제됨] 불필요한 ID 변경 코드들 (에러 원인)
    # op.alter_column('bookings', 'time_slot_id', ...)
    # op.alter_column('calendars', 'id', ...)
    
    op.create_foreign_key(None, 'calendars', 'users', ['host_id'], ['id'])
    op.add_column('posts', sa.Column('time_slot_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('when', sa.Date(), nullable=True))
    
    # [삭제됨] 불필요한 ID 변경 코드들 (에러 원인)
    # op.alter_column('time_slots', 'id', ...)
    # op.alter_column('time_slots', 'calendar_id', ...)
    
    op.create_foreign_key(None, 'time_slots', 'calendars', ['calendar_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'CUSTOMER'::text"))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint('uq_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'CUSTOMER'::text"))
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    
    # [삭제됨] ID 변경 롤백 코드 삭제
    # op.alter_column('time_slots', 'calendar_id', ...)
    # op.alter_column('time_slots', 'id', ...)
    
    op.drop_column('posts', 'when')
    op.drop_column('posts', 'time_slot_id')
    op.drop_constraint(None, 'calendars', type_='foreignkey')
    
    # [삭제됨] ID 변경 롤백 코드 삭제
    # op.alter_column('calendars', 'id', ...)
    # op.alter_column('bookings', 'time_slot_id', ...)
    
    op.drop_column('bookings', 'type')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_match_requests_post_id'), table_name='match_requests')
    op.drop_index(op.f('ix_match_requests_guest_id'), table_name='match_requests')
    op.drop_table('match_requests')

    booking_type_enum = sa.Enum('LESSON', 'HOLIDAY', name='bookingtype')
    booking_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###