name: CI (Tests)

on:
  push:
    branches:
      - "main"
      - "staging"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Initialize Database
        env:
          PYTHONPATH: .
          PGSSLMODE: disable  
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
          AWS_ACCESS_KEY_ID: testing
          AWS_SECRET_ACCESS_KEY: testing
          AWS_SECURITY_TOKEN: testing
          AWS_SESSION_TOKEN: testing
          AWS_DEFAULT_REGION: ap-northeast-2
          SUPABASE_URL: https://example.supabase.co
          SUPABASE_ANON_KEY: dummy
          SUPABASE_JWT_SECRET: dummy
        run: poetry run python -m scripts.reset_db

      - name: Run tests
        env:
          PYTHONPATH: .
          PGSSLMODE: disable
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
          SUPABASE_URL: https://example.supabase.co
          SUPABASE_ANON_KEY: dummy
          SUPABASE_JWT_SECRET: dummy
          AWS_ACCESS_KEY_ID: testing
          AWS_SECRET_ACCESS_KEY: testing
          AWS_SECURITY_TOKEN: testing
          AWS_SESSION_TOKEN: testing
          AWS_DEFAULT_REGION: ap-northeast-2
        run: poetry run pytest -q