name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'  # frontend 폴더 안의 파일이 바뀔 때만 작동
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend  # 명령어를 frontend 폴더 안에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 설치한 버전과 맞춤
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build project
        run: npm run build