name: Orchestrator CI

on:
  pull_request:
    branches: ["staging"]

jobs:
  # 변경된 파일 경로 분석
  changes:
    name: 🔍 Check Changed Paths
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      root: ${{ steps.filter.outputs.root }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Path Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            root:
              - 'README.md'
              - 'Makefile'
              - '.github/workflows/**'
              - '.gitignore'

  # Backend CI 호출 (backend 폴더 혹은 root 파일 수정 시)
  backend-ci:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.root == 'true' }}
    uses: ./.github/workflows/backend-CI.yml
    secrets: inherit

  # Frontend CI 호출 (frontend 폴더 혹은 root 파일 수정 시)
  frontend-ci:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.root == 'true' }}
    uses: ./.github/workflows/frontend-CI.yml
    secrets: inherit